app/Http/routes.php
<?php


Session::set('currency', 'usd');
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
 *  Set up locale and locale_prefix if other language is selected
 */
if (in_array(Request::segment(1), Config::get('app.alt_langs'))) {

    App::setLocale(Request::segment(1));

    Config::set('app.locale_prefix', Request::segment(1));
}


/*
 * Set up route patterns - patterns will have to be the same as in translated route for current language
 */
foreach(Lang::get('url') as $k => $v) {

    Route::pattern($k, $v);
}

Route::get('make_dir', function () {

    $dir = date('Y/m/d');

    File::makeDirectory($dir, 0755, true);

    return 'success';
});

Route::get('test_pdf', function () { 

    #return view('emails.enquiry');

    $pdf = PDF::loadView('pdf.property_new');

    return $pdf->stream();

});

// API
Route::group(['prefix' => 'api'], function() {

    Route::resource('branch', 'BranchController');

    Route::resource('city', 'CityController');

    Route::resource('message', 'ContactController');

    Route::resource('country', 'CountryController');

    Route::resource('customer', 'CustomerController');

    Route::resource('enquiry', 'EnquiryController');

    Route::resource('locale', 'LocaleController');

    Route::resource('log_customer', 'LogCustomerController');

    Route::resource('log_user', 'LogUserController');

    Route::resource('notification', 'NotificationController');

    Route::resource('page', 'PageController');

    Route::resource('page_locale', 'PageLocaleController');

    Route::resource('page_meta', 'PageMetaController');

    Route::resource('page_term', 'PageTermController');

    Route::resource('post', 'PostController');

    Route::resource('post_locale', 'PostLocaleController');

    Route::resource('post_meta', 'PostMetaController');

    Route::resource('post_term', 'PostTermController');

    Route::resource('properties', 'PropertyController');

    Route::resource('property_locale', 'PropertyLocaleController');

    Route::resource('property_meta', 'PropertyMetaController');

    Route::resource('property_term', 'PropertyTermController');

    Route::resource('province', 'ProvinceController');

    Route::resource('role', 'RoleController');

    Route::resource('category', 'CategoryController');

    Route::resource('testimony', 'TestimonyController');

    Route::resource('newsletter', 'NewsletterController');

    Route::resource('user', 'UserController');

    Route::resource('wishlist', 'WishlistController');

    Route::resource('attachment', 'AttachmentController');

    Route::resource('setting', 'SettingController');

    Route::get('attachment/get/image', ['as' => 'api.attachment.get.image', 'uses' => 'AttachmentController@getImage']);

    Route::post('upload/image', ['as' => 'api.attachment.upload.image', 'uses' => 'AttachmentController@uploadImage']);

    Route::post('upload/file', ['as' => 'api.attachment.upload.file', 'uses' => 'AttachmentController@uploadFile']);

    Route::post('sellproperty', ['as' => 'sellproperty.store', 'uses' => 'PropertyController@sellProperty']);

    Route::post('property/delete/{id}', ['as' => 'api.property.delete', 'uses' => 'PropertyController@delete']);

    Route::post('property_meta/thumb', ['as' => 'api.thumb.store', 'uses' => 'PropertyMetaController@thumb']);

    Route::post('translate/{to}',['as' => 'api.translate', 'uses' => 'BingTranslateController@trans']);

    Route::post('property/remove', ['as' => 'api.property.remove', 'uses' => 'PropertyController@remove']);

    Route::post('property/set_status', ['as' => 'api.property.set_status', 'uses' => 'PropertyController@setStatus']);

    Route::post('enquiry/remove', ['as' => 'api.enquiry.remove', 'uses' => 'EnquiryController@remove']);

    Route::post('customer/remove', ['as' => 'api.customer.remove', 'uses' => 'CustomerController@remove']);

    Route::post('testimony/remove', ['as' => 'api.testimony.remove', 'uses' => 'TestimonyController@remove']);

    Route::post('contact/remove', ['as' => 'api.contact.remove', 'uses' => 'ContactController@remove']);

    Route::post('newsletter/remove', ['as' => 'api.newsletter.remove', 'uses' => 'NewsletterController@remove']);

    Route::post('post/remove', ['as' => 'api.post.remove', 'uses' => 'PostController@remove']);

    Route::post('user/remove', ['as' => 'api.user.remove', 'uses' => 'UserController@remove']);

    Route::post('branch/remove', ['as' => 'api.branch.remove', 'uses' => 'BranchController@remove']);


});


// Back-End
Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => 'admin'], function () {

        // dashbord
        Route::get('/', function() {

            return redirect('/admin/dashboard');
        });

        Route::get('dashboard',['as' => 'admin.dashboard', 'uses' => 'AdminController@dashboard']);

        // property
        Route::get('properties/{term?}',['as' => 'admin.properties', 'uses' => 'AdminController@properties'])->where('term', '(.*)');

        // enquiry
        Route::get('enquiries/{term?}',['as' => 'admin.enquiries', 'uses' => 'AdminController@enquiries']);


        // customer
        Route::get('customers/{term?}',['as' => 'admin.customers', 'uses' => 'AdminController@customers']);

        // Page
        Route::get('pages/{term?}',['as' => 'admin.pages', 'uses' => 'AdminController@pages']);

        // Post
        Route::get('blog/{term?}',['as' => 'admin.posts', 'uses' => 'AdminController@posts']);

        // my-account
        Route::get('my-account',['as' => 'admin.my_account', 'uses' => 'AdminController@my_account']);

        // accounts
        Route::get('accounts',['as' => 'admin.accounts', 'uses' => 'AdminController@accounts']);

        // branches
        Route::get('branches',['as' => 'admin.branches', 'uses' => 'AdminController@branches']);

        // setting
        Route::get('settings',['as' => 'admin.setting', 'uses' => 'AdminController@settings']);

        // about
        Route::get('about',['as' => 'admin.about', 'uses' => 'AdminController@about']);


        // PDF Export
        Route::group(['prefix' => 'pdf'], function () {

            Route::get('property/{id}', ['as' => 'admin.pdf.property', 'uses' => 'PdfController@property']);
        });

        Route::group(['prefix' => 'export'], function () {

            Route::group(['prefix' => 'property'], function () {

                Route::post('csv', ['as' => 'export.property.csv', 'uses' => 'PropertyController@export']);

                Route::post('pdf', ['as' => 'export.property.pdf', 'uses' => 'PropertyController@exportPDF']);

                Route::get('pdf', function () {

                    $property = \App\Property::find(1);

                    return view('pdf.property', compact('property'));
                });
            });

            Route::group(['prefix' => 'enquiry'], function () {

                Route::post('csv', ['as' => 'export.enquiry.csv', 'uses' => 'EnquiryController@export']);
            });

            Route::group(['prefix' => 'customer'], function () {

                Route::post('csv', ['as' => 'export.customer.csv', 'uses' => 'CustomerController@export']);
            });

            Route::group(['prefix' => 'testimony'], function () {

                Route::post('csv', ['as' => 'export.testimony.csv', 'uses' => 'TestimonyController@export']);
            });

            Route::group(['prefix' => 'contact'], function () {

                Route::post('csv', ['as' => 'export.contact.csv', 'uses' => 'ContactController@export']);
            });

            Route::group(['prefix' => 'post'], function () {

                Route::post('csv', ['as' => 'export.post.csv', 'uses' => 'PostController@export']);
            });

            Route::group(['prefix' => 'page'], function () {

                Route::post('csv', ['as' => 'export.page.csv', 'uses' => 'PageController@export']);
            });

            Route::group(['prefix' => 'user'], function () {

                Route::post('csv', ['as' => 'export.user.csv', 'uses' => 'UserController@export']);
            });

            Route::group(['prefix' => 'branch'], function () {

                Route::post('csv', ['as' => 'export.branch.csv', 'uses' => 'BranchController@export']);
            });

            Route::group(['prefix' => 'newsletter'], function () {

                Route::post('csv', ['as' => 'export.newsletter.csv', 'uses' => 'NewsletterController@export']);
            });

        });

        // Support Ticket
        Route::post('send_ticket', ['as' => 'admin.send_ticket' , 'uses' => function (Illuminate\Http\Request $request) {

            $user = \Auth::user()->get();

            Mail::raw($request->message, function ($m) use ($user, $request) {

                $m->from($user->email, $user->firstname);

                $m->to(\Config::get('mail.support'), 'Support')->subject('KIBARER Ticket: '. $request->subject);

            });

            return response()->json(array('status' => 200, 'monolog' => array('title' => 'success', 'message' => 'Your message has been sent successfully.')));
            // return redirect()->back();

        }]);

    });

});


// User Auth
Route::controllers([

    'auth' => 'Auth\AuthController',

    'password' => 'Auth\PasswordController',
]);


// Front-End
Route::group(['prefix' => Config::get('app.locale_prefix')], function() {

    Route::get('currency/{currrency}', ['as' => 'set_currency', 'uses' => function ($currency) {

        Session::set('currency', $currency);

        // return Session::get('currency');

        return redirect()->back();
    }]);

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Contact;
use App\Services\GetBaseCRM;
use App\Services\UserTrack;

use Mail;

class ContactController extends Controller
{

    protected $user_track;


    function __construct()
    {
        $this->user_track = new UserTrack();
    }

    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $category = $request->category;
        $status = $request->status;

        // datatable parameter
        $draw = $request->draw;
        $start = $request->start;
        $length = $request->length;
        $search = $request->search['value'];

        // sorting
        $column = 'id';
        $sort = $request->order[0]['dir'] ? $request->order[0]['dir'] : 'desc'; //asc

        // new object
        $contacts = new Contact;

        // searching
        if ($search) {

            $contacts = $contacts->where(function ($q) use ($search) {
                    $q->where('contacts.email', 'like', $search . '%')
                        ->orWhere('contacts.message', 'like', $search . '%');
                });
        }

        // total records
        $count = $contacts->count();

        // pagination
        $contacts = $contacts->take($length)->skip($start);

        // order
        if ($request->order[0]['column']) {

            $column = $request->columns[$request->order[0]['column']]['data'];

            $contacts = $contacts->orderBy('contacts.' . $column, $sort);

        } else {

            $contacts = $contacts->orderBy('contacts.' . $column, $sort);
        }

        // get data
        $contacts = $contacts->get();

        // datatable response
        $respose = [
                "draw" => $draw,
                "recordsTotal" => $count,
                "recordsFiltered" => $count,
                "data" => $contacts

            ];

        return $respose;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'email' => 'email|required',
            'firstname' => 'required',
            'lastname' => 'required',
            'g-recaptcha-response' => 'required|recaptcha'
        ]);

        if ($validator->fails()) {
            return response()->json(array('status' => 500, 'monolog' => array('title' => 'errors', 'message' => $validator->errors() )));
        }

        /*
        $contact = new Contact;

        $contact->firstname = $request->firstname;
        $contact->lastname = $request->lastname;
        $contact->email = $request->email;
        $contact->message = $request->message;

        $contact->save();

        $this->email($contact);
        */

        // Add this contact to CRM
        $data = $request->all();
        $data['ip'] = $request->server('SERVER_ADDR');
        $data['lang'] = substr($request->server('HTTP_ACCEPT_LANGUAGE'), 0, 2);
        $data['tags'] = $this->user_track->get();
        $crm = new GetBaseCRM;
        $crm->customer_add($data);

        return response()->json(array('status' => 200, 'monolog' => array('title' => 'success', 'message' => 'success')));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $contact = Contact::find($id);

        $contact->delete();

        return response()->json(array('status' => 200, 'monolog' => array('title' => 'delete success', 'message' => 'object has been deleted'), 'id' => $id));
    }

    public function email($contact)
    {
        $email = \Config::get('mail.contact');

        Mail::send('emails.contact', ['contact' => $contact], function($message) use ($email) {

            $message->from('boris@kesato.com', 'Kibarer');

            $message->to($email, $email)->subject('Contact Kibarer');
        });

        return true;
    }

    public function export(Request $request)
    {
        $ids = explode(',', $request->id);

        $admin = \Auth::user()->get();

        $file_name = $admin->id . '-message';

        $take = ($request->take) ? $request->take : 'all';

        $contacts = new Contact;

        if ($request->take == 'selected') {

            $contacts = $contacts->whereIn('contacts.id', $ids);

            // $contacts = $contacts->take($take);
        }

        $contacts = $contacts->orderBy('id', 'desc');

        $contacts = $contacts->get();

        $data = json_decode(json_encode($contacts), true);

        \Excel::create($file_name, function($excel) use ($data) {

            $excel->sheet('Sheet1', function($sheet) use ($data) {

                $sheet->setOrientation('landscape');

                $sheet->fromArray($data);

            });

        })
        // ->export('csv');
        ->store('csv', 'export/csv');

        return $file_name . '.csv';
    }

    public function remove(Request $request)
    {
        //

        foreach ($request->id as $id) {
            
            $contact = Contact::find($id);

            $contact->delete();
        }

        return response()->json(array('status' => 200, 'monolog' => array('title' => 'delete success', 'message' => 'object has been deleted'), 'id' => $request->id));
    }

}

resources/views/admin/pages/contact/create.blade.php
@extends('admin.master')
@section('page', 'properties')

@section('content')
<h3>Add Enquiry</h3>
<br>

{!! Form::open(['url' => route('api.enquiry.store')]) !!}


    <div class="m-input-group fwidth flexbox justify-between">
        <div class="m-input-wrapper w50-6">
            <input type="text" name="property_id" required>
            <label for="title">Property ID</label>
        </div>
        <div class="m-input-wrapper w50-6">
            <input type="text" name="subject" required>
            <label for="title">subject</label>
        </div>
    </div>

    <div class="m-input-group fwidth flexbox justify-between">
        <div class="m-input-wrapper w50-6">
            <input type="text" name="firstname" required>
            <label for="title">firstname</label>
        </div>
        <div class="m-input-wrapper w50-6">
            <input type="text" name="lastname" required>
            <label for="title">lastname</label>
        </div>
    </div>

    <div class="m-input-group fwidth flexbox justify-between">
        <div class="m-input-wrapper w50-6">
            <input type="text" name="phone" required>
            <label for="title">phone</label>
        </div>
        <div class="m-input-wrapper w50-6">
            <input type="text" name="email" required>
            <label for="title">email</label>
        </div>
    </div>

    <div class="m-input-group textarea fwidth flexbox flexbox-wrap">
        <h3 class="input-group-title">Comment</h3>
        <div class="input-wrapper fwidth">
            <textarea name="content" id="property-input-description" rows="10" style="padding-top: 0"></textarea>
        </div>
    </div>

    <m-buttons flexbox justify-end>
        <m-button plain onclick="window.history.back()">cancel</m-button>
        <m-button save-form plain>save</m-button>
    </m-buttons>

{!! Form::close() !!}

@endsection

@section('scripts')
<script>

    $(document).ready(function() {
        
        $(document).on('click', '[save-form]', function(event) {
            event.preventDefault();
            
            console.log('save clicked!');

            var url = "{{ route('api.enquiry.store') }}";
            var fd = new FormData($('form')[0]);

            NProgress.start();

            Ajax.post(url, fd, saved);
            

            NProgress.done();
        });
    });

    function saved() {

        $('input').val('');

        $('textarea').val('');

        location.reload();
    }

</script>
@endsection

resources/views/admin/pages/contact/edit.blade.php
@extends('admin.master')
@section('page', 'properties')

@section('content')
<h3>Edit Enquiry</h3>
<br>

{!! Form::open(['url' => route('api.enquiry.store')]) !!}

    {{ method_field('PUT') }}
    <div class="m-input-group fwidth flexbox justify-between">
        <div class="m-input-wrapper w50-6">
            <input value="{{ $enquiry->property_id }}" type="text" name="property_id" required>
            <label for="title">Property ID</label>
        </div>
        <div class="m-input-wrapper w50-6">
            <input value="{{ $enquiry->subject }}" type="text" name="subject" required>
            <label for="title">subject</label>
        </div>
    </div>

    <div class="m-input-group fwidth flexbox justify-between">
        <div class="m-input-wrapper w50-6">
            <input value="{{ $enquiry->firstname }}" type="text" name="firstname" required>
            <label for="title">firstname</label>
        </div>
        <div class="m-input-wrapper w50-6">
            <input value="{{ $enquiry->lastname }}" type="text" name="lastname" required>
            <label for="title">lastname</label>
        </div>
    </div>

    <div class="m-input-group fwidth flexbox justify-between">
        <div class="m-input-wrapper w50-6">
            <input value="{{ $enquiry->phone }}" type="text" name="phone" required>
            <label for="title">phone</label>
        </div>
        <div class="m-input-wrapper w50-6">
            <input value="{{ $enquiry->email }}" type="text" name="email" required>
            <label for="title">email</label>
        </div>
    </div>

    <div class="m-input-group textarea fwidth flexbox flexbox-wrap">
        <h3 class="input-group-title">Comment</h3>
        <div class="input-wrapper fwidth">
            <textarea name="content" id="property-input-description" rows="10" style="padding-top: 0">{{ $enquiry->content }}</textarea>
        </div>
    </div>

    <m-buttons flexbox justify-end>
        <m-button plain onclick="window.history.back()">cancel</m-button>
        <m-button save-form plain>save</m-button>
    </m-buttons>

{!! Form::close() !!}

@endsection

@section('scripts')
<script>

    $(document).ready(function() {
        
        $(document).on('click', '[save-form]', function(event) {
            event.preventDefault();
            
            console.log('save clicked!');

            var url = "{{ route('api.enquiry.update', $enquiry->id) }}";
            var fd = new FormData($('form')[0]);

            NProgress.start();

            Ajax.post(url, fd, saved);
            

            NProgress.done();
        });
    });

    function saved() {

        location.reload();
    }

</script>
@endsection

resources/views/admin/pages/contact/listing.blade.php
@extends('admin.master')
@section('page', 'properties')

@section('fab')

<!-- <m-fab salmon class="modal-open" data-target="#message-add"><i class="material-icons">add</i></m-fab> -->
<!-- <a href="{{ route('admin.customers', ['term' => 'messages', 'action' => 'create']) }}"><m-fab salmon data-target="#message-add"><i class="material-icons">add</i></m-fab></a> -->

@stop

@section('content')

<!-- <a class="export-csv"><i class="material-icons">open_in_new</i> <label style="position: relative; top: -5px">Export CSV</label></a> -->
<div style="margin-top: 30px"></div>
<m-template list class="message-wrapper">

    <table data-selected="" data-token="{{ csrf_token() }}">
        <thead>
            <th width="15px"><input type="checkbox" class="check-all visible"></th>
            <td>firstname</td>
            <td>lastname</td>
            <td>email</td>
            <td>message</td>
            <td>Created</td>
            <td>Action</td>
        </thead>

    </table>


</m-template>

@endsection

@section('modal')
<m-modal-wrapper id="csv-export-modal">

    <div class="modal-window" style="max-width: 640px" data-id="">
        <h3>CSV Export Configuration</h3>

        {!! Form::open(['url' => route('export.contact.csv'), 'id' => 'export-csv']) !!}

        <input id="form-csv-id" type="hidden" name="id" value="">

        <m-input-group fwidth flexwrap justify-between>
            <m-input select w50-6>
                <select name="take" id="take">
                    <option value="selected" selected>selected</option>
                    <option value="all">all</option>
                </select>
                <label for="title">Rows</label>
            </m-input>
        </m-input-group>

        <m-buttons flexbox justify-end style="margin-top: 16px;">
            <m-button plain modal-close>cancel</m-button>
            <m-button export-csv plain>export</m-button>
        </m-buttons>

        {!! Form::close() !!}
    </div>

</m-modal-wrapper>
@endsection

@section('scripts')

<script>
    // Matter.admin.enquiries();

    $(document).ready(function() {

        $(document).on('click', '[delete]', function(event) {
            event.preventDefault();

            var id = $(this).parent().attr('data-id');            
            var url = "{{ route('api.message.destroy', $id = null) }}/" + id;
            var method = 'delete';
            var token = "{{ csrf_token() }}";

            Monolog.confirm('delete item', 'are you sure to delete this item? this cannot be undone', function() {
                NProgress.start();
                $.post(url, {_method: method, _token: token}, function(data, textStatus, xhr) {
                    
                    switch(data.status) {

                        case 200:

                            Monolog.notify(data.monolog.title, data.monolog.message);

                            removeItem(data);

                            break;

                        default:

                            Monolog.notify(data.monolog.title, data.monolog.message);

                            consoleLog(data);
                    }
                });
            });

        });

        var table_url = "{!! $api_url !!}";
        var table_columns = [
                {
                    "orderable": false,
                    "data": "id",
                    "render": function (data, type, row) {
                        return '<input value="' + data + '" type="checkbox" class="check-item visible">';
                    }
                },
                {"data": "firstname"},
                {"data": "lastname"},
                {"data": "email"},
                {"data": "message"},
                {
                    "data": "created_at",
                    "render": function (data, type, row) {
                        var date = new Date(data);
                        var newDate = date.toISOString().split('T')[0];
                        return newDate;
                    }
                },
                {
                    "orderable": false,
                    "data": 'id',
                    "render": function (data, type, row) {

                        return ''
                        + '<m-table-list-more>'
                            + '<i class="material-icons">more_horiz</i>'
                            + '<m-list-menu data-id="'+ data +'">'
                                // + '<a href="'+ baseUrl +'/admin/customers/messages?action=edit&id='+ data +'"><m-list-menu-item edit data-source="property/get" data-function="populatePropertyEdit">EDIT</m-list-menu-item></a>'
                                + '<m-list-menu-item delete>DELETE</m-list-menu-item>'
                            + '</m-list-menu>'
                        + '</m-table-list-more>';
                    }
                }
            ];
        var table_element = $('table');
        var table_order = [[ 0, "desc" ]];
        var delete_url = "{{ route('api.contact.remove') }}";

        var action_url = {'delete': delete_url};

        Listing.render(table_url, table_element, table_columns, table_order);

        Listing.action(action_url, false, false, false);

        // $('table').DataTable({
        //     "processing": true,
        //     "serverSide": true,            
        //     "ajax": {
        //         "url": "{!! $api_url !!}",
        //         "type": "GET"
        //     },
        //     "deferRender": true,
        //     "columns": [
        //         {
        //             "orderable": false,
        //             "data": "id",
        //             "render": function (data, type, row) {
        //                 return '<input value="' + data + '" type="checkbox" class="check-item visible">';
        //             }
        //         },
        //         {"data": "firstname"},
        //         {"data": "lastname"},
        //         {"data": "email"},
        //         {"data": "message"},
        //         {
        //             "data": "created_at",
        //             "render": function (data, type, row) {
        //                 var date = new Date(data);
        //                 var newDate = date.toISOString().split('T')[0];
        //                 return newDate;
        //             }
        //         },
        //         {
        //             "orderable": false,
        //             "data": 'id',
        //             "render": function (data, type, row) {

        //                 return ''
        //                 + '<m-table-list-more>'
        //                     + '<i class="material-icons">more_horiz</i>'
        //                     + '<m-list-menu data-id="'+ data +'">'
        //                         // + '<a href="'+ baseUrl +'/admin/customers/messages?action=edit&id='+ data +'"><m-list-menu-item edit data-source="property/get" data-function="populatePropertyEdit">EDIT</m-list-menu-item></a>'
        //                         + '<m-list-menu-item delete>DELETE</m-list-menu-item>'
        //                     + '</m-list-menu>'
        //                 + '</m-table-list-more>';
        //             }
        //         }
        //     ],
        //     "createdRow": function ( row, data, index ) {

        //         $('td:last-child', row).attr('button', '');

        //         $(row).attr('id', 'row-item-' + data.id);
        //     },
        //     "order": [[ 0, "desc" ]]
        // });

    });

    function removeItem(data) {

        var id = data.id;

        $('#row-item-' + id).remove();

        NProgress.done();
    }

    $(document).on('click', '.export-csv', function(event) {
        event.preventDefault();
        /* Act on the event */

        modalOpen('#csv-export-modal');
    });

    $(document).on('click', '[export-csv]', function(event) {
        event.preventDefault();

        console.log('export clicked!');

        NProgress.start();

        var frm = $('#export-csv'),
        url = frm.attr('action');
        data = frm.serialize();

        $.post(url, data, function(data, textStatus, xhr) {

            console.log(data);

            window.location.href = "{{ url('export/csv') }}/" + data;

            NProgress.done();

        });

    });

</script>

@endsection