app/Http/routes.php
<?php


Session::set('currency', 'usd');
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
 *  Set up locale and locale_prefix if other language is selected
 */
if (in_array(Request::segment(1), Config::get('app.alt_langs'))) {

    App::setLocale(Request::segment(1));

    Config::set('app.locale_prefix', Request::segment(1));
}


/*
 * Set up route patterns - patterns will have to be the same as in translated route for current language
 */
foreach(Lang::get('url') as $k => $v) {

    Route::pattern($k, $v);
}

Route::get('make_dir', function () {

    $dir = date('Y/m/d');

    File::makeDirectory($dir, 0755, true);

    return 'success';
});

Route::get('test_pdf', function () { 

    #return view('emails.enquiry');

    $pdf = PDF::loadView('pdf.property_new');

    return $pdf->stream();

});

// API
Route::group(['prefix' => 'api'], function() {

    Route::resource('branch', 'BranchController');

    Route::resource('city', 'CityController');

    Route::resource('message', 'ContactController');

    Route::resource('country', 'CountryController');

    Route::resource('customer', 'CustomerController');

    Route::resource('enquiry', 'EnquiryController');

    Route::resource('locale', 'LocaleController');

    Route::resource('log_customer', 'LogCustomerController');

    Route::resource('log_user', 'LogUserController');

    Route::resource('notification', 'NotificationController');

    Route::resource('page', 'PageController');

    Route::resource('page_locale', 'PageLocaleController');

    Route::resource('page_meta', 'PageMetaController');

    Route::resource('page_term', 'PageTermController');

    Route::resource('post', 'PostController');

    Route::resource('post_locale', 'PostLocaleController');

    Route::resource('post_meta', 'PostMetaController');

    Route::resource('post_term', 'PostTermController');

    Route::resource('properties', 'PropertyController');

    Route::resource('property_locale', 'PropertyLocaleController');

    Route::resource('property_meta', 'PropertyMetaController');

    Route::resource('property_term', 'PropertyTermController');

    Route::resource('province', 'ProvinceController');

    Route::resource('role', 'RoleController');

    Route::resource('category', 'CategoryController');

    Route::resource('testimony', 'TestimonyController');

    Route::resource('newsletter', 'NewsletterController');

    Route::resource('user', 'UserController');

    Route::resource('wishlist', 'WishlistController');

    Route::resource('attachment', 'AttachmentController');

    Route::resource('setting', 'SettingController');

    Route::get('attachment/get/image', ['as' => 'api.attachment.get.image', 'uses' => 'AttachmentController@getImage']);

    Route::post('upload/image', ['as' => 'api.attachment.upload.image', 'uses' => 'AttachmentController@uploadImage']);

    Route::post('upload/file', ['as' => 'api.attachment.upload.file', 'uses' => 'AttachmentController@uploadFile']);

    Route::post('sellproperty', ['as' => 'sellproperty.store', 'uses' => 'PropertyController@sellProperty']);

    Route::post('property/delete/{id}', ['as' => 'api.property.delete', 'uses' => 'PropertyController@delete']);

    Route::post('property_meta/thumb', ['as' => 'api.thumb.store', 'uses' => 'PropertyMetaController@thumb']);

    Route::post('translate/{to}',['as' => 'api.translate', 'uses' => 'BingTranslateController@trans']);

    Route::post('property/remove', ['as' => 'api.property.remove', 'uses' => 'PropertyController@remove']);

    Route::post('property/set_status', ['as' => 'api.property.set_status', 'uses' => 'PropertyController@setStatus']);

    Route::post('enquiry/remove', ['as' => 'api.enquiry.remove', 'uses' => 'EnquiryController@remove']);

    Route::post('customer/remove', ['as' => 'api.customer.remove', 'uses' => 'CustomerController@remove']);

    Route::post('testimony/remove', ['as' => 'api.testimony.remove', 'uses' => 'TestimonyController@remove']);

    Route::post('contact/remove', ['as' => 'api.contact.remove', 'uses' => 'ContactController@remove']);

    Route::post('newsletter/remove', ['as' => 'api.newsletter.remove', 'uses' => 'NewsletterController@remove']);

    Route::post('post/remove', ['as' => 'api.post.remove', 'uses' => 'PostController@remove']);

    Route::post('user/remove', ['as' => 'api.user.remove', 'uses' => 'UserController@remove']);

    Route::post('branch/remove', ['as' => 'api.branch.remove', 'uses' => 'BranchController@remove']);


});


// Back-End
Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => 'admin'], function () {

        // dashbord
        Route::get('/', function() {

            return redirect('/admin/dashboard');
        });

        Route::get('dashboard',['as' => 'admin.dashboard', 'uses' => 'AdminController@dashboard']);

        // property
        Route::get('properties/{term?}',['as' => 'admin.properties', 'uses' => 'AdminController@properties'])->where('term', '(.*)');

        // enquiry
        Route::get('enquiries/{term?}',['as' => 'admin.enquiries', 'uses' => 'AdminController@enquiries']);


        // customer
        Route::get('customers/{term?}',['as' => 'admin.customers', 'uses' => 'AdminController@customers']);

        // Page
        Route::get('pages/{term?}',['as' => 'admin.pages', 'uses' => 'AdminController@pages']);

        // Post
        Route::get('blog/{term?}',['as' => 'admin.posts', 'uses' => 'AdminController@posts']);

        // my-account
        Route::get('my-account',['as' => 'admin.my_account', 'uses' => 'AdminController@my_account']);

        // accounts
        Route::get('accounts',['as' => 'admin.accounts', 'uses' => 'AdminController@accounts']);

        // branches
        Route::get('branches',['as' => 'admin.branches', 'uses' => 'AdminController@branches']);

        // setting
        Route::get('settings',['as' => 'admin.setting', 'uses' => 'AdminController@settings']);

        // about
        Route::get('about',['as' => 'admin.about', 'uses' => 'AdminController@about']);


        // PDF Export
        Route::group(['prefix' => 'pdf'], function () {

            Route::get('property/{id}', ['as' => 'admin.pdf.property', 'uses' => 'PdfController@property']);
        });

        Route::group(['prefix' => 'export'], function () {

            Route::group(['prefix' => 'property'], function () {

                Route::post('csv', ['as' => 'export.property.csv', 'uses' => 'PropertyController@export']);

                Route::post('pdf', ['as' => 'export.property.pdf', 'uses' => 'PropertyController@exportPDF']);

                Route::get('pdf', function () {

                    $property = \App\Property::find(1);

                    return view('pdf.property', compact('property'));
                });
            });

            Route::group(['prefix' => 'enquiry'], function () {

                Route::post('csv', ['as' => 'export.enquiry.csv', 'uses' => 'EnquiryController@export']);
            });

            Route::group(['prefix' => 'customer'], function () {

                Route::post('csv', ['as' => 'export.customer.csv', 'uses' => 'CustomerController@export']);
            });

            Route::group(['prefix' => 'testimony'], function () {

                Route::post('csv', ['as' => 'export.testimony.csv', 'uses' => 'TestimonyController@export']);
            });

            Route::group(['prefix' => 'contact'], function () {

                Route::post('csv', ['as' => 'export.contact.csv', 'uses' => 'ContactController@export']);
            });

            Route::group(['prefix' => 'post'], function () {

                Route::post('csv', ['as' => 'export.post.csv', 'uses' => 'PostController@export']);
            });

            Route::group(['prefix' => 'page'], function () {

                Route::post('csv', ['as' => 'export.page.csv', 'uses' => 'PageController@export']);
            });

            Route::group(['prefix' => 'user'], function () {

                Route::post('csv', ['as' => 'export.user.csv', 'uses' => 'UserController@export']);
            });

            Route::group(['prefix' => 'branch'], function () {

                Route::post('csv', ['as' => 'export.branch.csv', 'uses' => 'BranchController@export']);
            });

            Route::group(['prefix' => 'newsletter'], function () {

                Route::post('csv', ['as' => 'export.newsletter.csv', 'uses' => 'NewsletterController@export']);
            });

        });

        // Support Ticket
        Route::post('send_ticket', ['as' => 'admin.send_ticket' , 'uses' => function (Illuminate\Http\Request $request) {

            $user = \Auth::user()->get();

            Mail::raw($request->message, function ($m) use ($user, $request) {

                $m->from($user->email, $user->firstname);

                $m->to(\Config::get('mail.support'), 'Support')->subject('KIBARER Ticket: '. $request->subject);

            });

            return response()->json(array('status' => 200, 'monolog' => array('title' => 'success', 'message' => 'Your message has been sent successfully.')));
            // return redirect()->back();

        }]);

    });

});


// User Auth
Route::controllers([

    'auth' => 'Auth\AuthController',

    'password' => 'Auth\PasswordController',
]);


// Front-End
Route::group(['prefix' => Config::get('app.locale_prefix')], function() {

    Route::get('currency/{currrency}', ['as' => 'set_currency', 'uses' => function ($currency) {

        Session::set('currency', $currency);

        // return Session::get('currency');

        return redirect()->back();
    }]);

resources/views/admin/pages/page/create.blade.php
@extends('admin.master')
@section('page', 'pages')

@section('content')
<h3>Add Page</h3>
<br>

{!! Form::open(['url' => route('api.page.store')]) !!}

    <m-caroussel>

        <m-caroussel-header class="flexbox justify-end">
            <m-caroussel-switch-wrapper class="flexbox">
                <?php $numberOfSlides = 4 ?>
                <m-caroussel-switch class="active">english</m-caroussel-switch>
                <m-caroussel-switch>french</m-caroussel-switch>
                <m-caroussel-switch>russian</m-caroussel-switch>
                <m-caroussel-switch>bahasa</m-caroussel-switch>
            </m-caroussel-switch-wrapper>
        </m-caroussel-header>

        <m-caroussel-body>
            <m-caroussel-slider class="flexbox align-start" style="width: <?= $numberOfSlides ?>00%;">

                @foreach(Config::get('app.alt_langs') as $locale)
                <m-caroussel-slide class="flexbox flexbox-wrap" id="caroussel-general" style="width: calc(100% / <?= $numberOfSlides ?>)">

                    <div class="m-input-group fwidth flexbox justify-between">                    
                        <div class="m-input-wrapper w50-6">
                            <input url-format data-target="#post-input-slug" type="text" name="title[{{ $locale }}]" id="post-input-title" required>
                            <label for="title">title</label>
                        </div>

                        <div class="m-input-wrapper w50-6">
                            <input type="text" name="slug[{{ $locale }}]" id="post-input-slug" required>
                            <label for="slug">url</label>
                        </div>
                    </div>

                    <div class="m-input-group fwidth flexbox justify-between">
                        <div class="m-input-wrapper w50-6">
                            <input type="text" name="meta_keyword[{{ $locale }}]" required>
                            <label for="title">keyword</label>
                        </div>
                        <div class="m-input-wrapper w50-6">
                            <input type="text" name="meta_description[{{ $locale }}]" required>
                            <label for="title">description</label>
                        </div>
                    </div>

                    <div class="m-input-group textarea fwidth flexbox flexbox-wrap">
                        <h3 class="input-group-title">content</h3>
                        <div class="input-wrapper fwidth">
                            <textarea rows="10" id="editor-{{ $locale }}" name="content[{{ $locale }}]" rows="10" style="padding-top: 0"></textarea>
                        </div>
                    </div>                

                </m-caroussel-slide>
                <script type="text/javascript">
                $(document).ready( function() {
                    $('#editor-{{ $locale }}').redactor({
                        imageUpload: "{{ route('api.attachment.upload.image', ['name' => 'page']) }}",
                        // fileUpload: "{{ route('api.attachment.upload.file', ['name' => 'post']) }}",
                        imageGetJson: "{{ route('api.attachment.get.image') }}",

                        minHeight: 300
                    });
                });
                </script>

                @endforeach

            </m-caroussel-slider>
        </m-caroussel-body>

    </m-caroussel>

    <div class="m-input-group fwidth flexbox justify-between">
        <div class="m-input-wrapper w50-6">
            <select name="status">
                <option value="1">publish</option>
                <option value="0">draft</option>
            </select>
            <label for="title">status</label>
        </div>
    </div>

    <m-buttons flexbox justify-end>
        <m-button plain onclick="window.history.back()">cancel</m-button>
        <m-button save-form plain>save</m-button>
    </m-buttons>

{!! Form::close() !!}

@endsection

@section('scripts')
<script>

    $(document).ready(function() {
        
        $(document).on('click', '[save-form]', function(event) {
            event.preventDefault();
            
            console.log('save clicked!');

            var url = "{{ route('api.page.store') }}";
            var fd = new FormData($('form')[0]);

            NProgress.start();

            Ajax.post(url, fd, saved);
            

            NProgress.done();
        });
    });

    function saved() {

        $('input').val('');

        $('textarea').val('');

        location.reload();
    }

</script>
@endsection

resources/views/admin/pages/page/edit.blade.php
@extends('admin.master')
@section('page', 'pages')

@section('content')
<h3>Add Page</h3>
<br>

{!! Form::open(['url' => route('api.page.update', $page->id)]) !!}

{!! method_field('PUT') !!}

    <m-caroussel>

        <m-caroussel-header class="flexbox justify-end">
            <m-caroussel-switch-wrapper class="flexbox">
                <?php $numberOfSlides = 4 ?>
                <m-caroussel-switch class="active">english</m-caroussel-switch>
                <m-caroussel-switch>french</m-caroussel-switch>
                <m-caroussel-switch>russian</m-caroussel-switch>
                <m-caroussel-switch>bahasa</m-caroussel-switch>
            </m-caroussel-switch-wrapper>
        </m-caroussel-header>

        <m-caroussel-body>
            <m-caroussel-slider class="flexbox align-start" style="width: <?= $numberOfSlides ?>00%;">

                @foreach(Config::get('app.alt_langs') as $locale)
                <?php $pageLocale = $page->pageLocales()->where('locale', $locale)->first(); ?>

                <m-caroussel-slide class="flexbox flexbox-wrap" id="caroussel-general" style="width: calc(100% / <?= $numberOfSlides ?>)">

                    <div class="m-input-group fwidth flexbox justify-between">                    
                        <div class="m-input-wrapper w50-6">
                            <input value="{{ $pageLocale->title or '' }}" url-format data-target="#page-input-slug-{{ $locale }}" type="text" name="title[{{ $locale }}]" id="page-input-title" required>
                            <label for="title">title</label>
                        </div>

                        <div class="m-input-wrapper w50-6">
                            <input value="{{ $pageLocale->slug or '' }}" type="text" name="slug[{{ $locale }}]" id="page-input-slug-{{ $locale }}" required>
                            <label for="slug">url</label>
                        </div>
                    </div>

                    <div class="m-input-group fwidth flexbox justify-between">
                        <div class="m-input-wrapper w50-6">
                            <input value="{{ $pageLocale->meta_keyword or '' }}" type="text" name="meta_keyword[{{ $locale }}]" required>
                            <label for="title">keyword</label>
                        </div>
                        <div class="m-input-wrapper w50-6">
                            <input value="{{ $pageLocale->meta_description or '' }}" type="text" name="meta_description[{{ $locale }}]" required>
                            <label for="title">description</label>
                        </div>
                    </div>

                    <div class="m-input-group textarea fwidth flexbox flexbox-wrap">
                        <h3 class="input-group-title">content</h3>
                        <div class="input-wrapper fwidth">
                            <textarea id="editor-{{ $locale }}" name="content[{{ $locale }}]" rows="10" style="padding-top: 0">{{ $pageLocale->content or '' }}</textarea>
                        </div>
                    </div>                

                </m-caroussel-slide>

                <script type="text/javascript">
                $(document).ready( function() {
                    $('#editor-{{ $locale }}').redactor({
                        imageUpload: "{{ route('api.attachment.upload.image', ['name' => 'page']) }}",
                        // fileUpload: "{{ route('api.attachment.upload.file') }}",
                        imageGetJson: "{{ route('api.attachment.get.image') }}",

                        minHeight: 300
                    });
                });
                </script>
                @endforeach

            </m-caroussel-slider>
        </m-caroussel-body>

    </m-caroussel>

    <div class="m-input-group fwidth flexbox justify-between">
        <div class="m-input-wrapper w50-6">
            <select name="status">
                <option value="1" {{ $page->status == 1 ? 'selected' : '' }}>publish</option>
                <option value="0" {{ $page->status == 0 ? 'selected' : '' }}>draft</option>
            </select>
            <label for="title">status</label>
        </div>
    </div>

    <m-buttons flexbox justify-end>
        <m-button plain onclick="window.history.back()">cancel</m-button>
        <m-button save-form plain>save</m-button>
    </m-buttons>

{!! Form::close() !!}

@endsection

@section('scripts')
<script>

    $(document).ready(function() {
        
        $(document).on('click', '[save-form]', function(event) {
            event.preventDefault();
            
            console.log('save clicked!');

            var url = "{{ route('api.page.update', $page->id) }}";
            var fd = new FormData($('form')[0]);

            NProgress.start();

            Ajax.post(url, fd, saved);
            

            NProgress.done();
        });
    });

    function saved() {

        // $('input').val('');

        // $('textarea').val('');

        location.reload();
    }

</script>
@endsection

resources/views/admin/pages/page/listing.blade.php
@extends('admin.master')
@section('page', 'properties')

@section('fab')

<!-- <m-fab salmon class="modal-open" data-target="#page-add"><i class="material-icons">add</i></m-fab> -->
<a href="{{ route('admin.pages', ['term' => null, 'action' => 'create']) }}"><m-fab salmon data-target="#page-add"><i class="material-icons">add</i></m-fab></a>

@stop

@section('content')

<a class="export-csv"><i class="material-icons">open_in_new</i> <label style="position: relative; top: -5px">Export CSV</label></a>

<m-template list class="page-wrapper">

    <table>
        <thead>
            <th width="15px"><input type="checkbox" class="check-all visible"></th>
            <td>title</td>
            <td>route</td>
            <td>status</td>
            <td>Created</td>
            <td>Action</td>
        </thead>

    </table>


</m-template>

@endsection

@section('modal')
<m-modal-wrapper id="csv-export-modal">

    <div class="modal-window" style="max-width: 640px" data-id="">
        <h3>CSV Export Configuration</h3>

        {!! Form::open(['url' => route('export.page.csv'), 'id' => 'export-csv']) !!}

        <m-input-group fwidth flexwrap justify-between>
            <m-input select w50-6>
                <select name="take" id="take">
                    <option value="10" selected>10</option>
                    <option value="100">100</option>
                    <option value="1000">1000</option>
                    <option value="all">all</option>
                </select>
                <label for="title">Rows</label>
            </m-input>
        </m-input-group>

        <m-buttons flexbox justify-end style="margin-top: 16px;">
            <m-button plain modal-close>cancel</m-button>
            <m-button export-csv plain>export</m-button>
        </m-buttons>

        {!! Form::close() !!}
    </div>

</m-modal-wrapper>
@endsection

@section('scripts')

<script>
    // Matter.admin.pages();

    $(document).ready(function() {

        $(document).on('click', '[delete]', function(event) {
            event.preventDefault();

            var id = $(this).parent().attr('data-id');            
            var url = "{{ route('api.page.destroy', $id = null) }}/" + id;
            var method = 'delete';
            var token = "{{ csrf_token() }}";

            Monolog.confirm('delete item', 'are you sure to delete this item? this cannot be undone', function() {
                NProgress.start();
                $.post(url, {_method: method, _token: token}, function(data, textStatus, xhr) {
                    
                    switch(data.status) {

                        case 200:

                            Monolog.notify(data.monolog.title, data.monolog.message);

                            removeItem(data);

                            break;

                        default:

                            Monolog.notify(data.monolog.title, data.monolog.message);

                            consoleLog(data);
                    }
                });
            });

        });

        $('table').DataTable({
            "processing": true,
            "serverSide": true,            
            "ajax": {
                "url": "{!! $api_url !!}",
                "type": "GET"
            },
            "deferRender": true,
            "columns": [
                {
                    "orderable": false,
                    "data": "id",
                    "render": function (data, type, row) {
                        return '<input value="' + data + '" type="checkbox" class="check-item visible">';
                    }
                },
                {"data": "page_locales.0.title"},
                {"data": "route"},
                {
                    "data": "status",
                    "render": function (data, type, row) {
                        return data == 1 ? 'publish' : 'draft';
                    }
                },
                {
                    "data": "created_at",
                    "render": function (data, type, row) {
                        var date = new Date(data);
                        var newDate = date.toISOString().split('T')[0];
                        return newDate;
                    }
                },
                {
                    "orderable": false,
                    "data": 'id',
                    "render": function (data, type, row) {

                        return ''
                        + '<m-table-list-more>'
                            + '<i class="material-icons">more_horiz</i>'
                            + '<m-list-menu data-id="'+ data +'">'
                                + '<a href="'+ baseUrl +'/admin/pages?action=edit&id='+ data +'"><m-list-menu-item edit data-source="property/get" data-function="populatePropertyEdit">EDIT</m-list-menu-item></a>'
                                + '<m-list-menu-item delete data-url="property/destroy">DELETE</m-list-menu-item>'
                            + '</m-list-menu>'
                        + '</m-table-list-more>';
                    }
                }
            ],
            "createdRow": function ( row, data, index ) {

                $('td:last-child', row).attr('button', '');

                $(row).attr('id', 'row-item-' + data.id);
            },
            "order": [[ 0, "desc" ]]
        });

    });

    function removeItem(data) {

        var id = data.id;

        $('#row-item-' + id).remove();

        NProgress.done();
    }

    $(document).on('click', '.export-csv', function(event) {
        event.preventDefault();
        /* Act on the event */

        modalOpen('#csv-export-modal');
    });

    $(document).on('click', '[export-csv]', function(event) {
        event.preventDefault();

        console.log('export clicked!');

        NProgress.start();

        var frm = $('#export-csv'),
        url = frm.attr('action');
        data = frm.serialize();

        $.post(url, data, function(data, textStatus, xhr) {

            console.log(data);

            window.location.href = "{{ url('export/csv') }}/" + data;

            NProgress.done();

        });

    });

</script>

@endsection