app/Http/routes.php
<?php


Session::set('currency', 'usd');
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
 *  Set up locale and locale_prefix if other language is selected
 */
if (in_array(Request::segment(1), Config::get('app.alt_langs'))) {

    App::setLocale(Request::segment(1));

    Config::set('app.locale_prefix', Request::segment(1));
}


/*
 * Set up route patterns - patterns will have to be the same as in translated route for current language
 */
foreach(Lang::get('url') as $k => $v) {

    Route::pattern($k, $v);
}

Route::get('make_dir', function () {

    $dir = date('Y/m/d');

    File::makeDirectory($dir, 0755, true);

    return 'success';
});

Route::get('test_pdf', function () { 

    #return view('emails.enquiry');

    $pdf = PDF::loadView('pdf.property_new');

    return $pdf->stream();

});

// API
Route::group(['prefix' => 'api'], function() {

    Route::resource('branch', 'BranchController');

    Route::resource('city', 'CityController');

    Route::resource('message', 'ContactController');

    Route::resource('country', 'CountryController');

    Route::resource('customer', 'CustomerController');

    Route::resource('enquiry', 'EnquiryController');

    Route::resource('locale', 'LocaleController');

    Route::resource('log_customer', 'LogCustomerController');

    Route::resource('log_user', 'LogUserController');

    Route::resource('notification', 'NotificationController');

    Route::resource('page', 'PageController');

    Route::resource('page_locale', 'PageLocaleController');

    Route::resource('page_meta', 'PageMetaController');

    Route::resource('page_term', 'PageTermController');

    Route::resource('post', 'PostController');

    Route::resource('post_locale', 'PostLocaleController');

    Route::resource('post_meta', 'PostMetaController');

    Route::resource('post_term', 'PostTermController');

    Route::resource('properties', 'PropertyController');

    Route::resource('property_locale', 'PropertyLocaleController');

    Route::resource('property_meta', 'PropertyMetaController');

    Route::resource('property_term', 'PropertyTermController');

    Route::resource('province', 'ProvinceController');

    Route::resource('role', 'RoleController');

    Route::resource('category', 'CategoryController');

    Route::resource('testimony', 'TestimonyController');

    Route::resource('newsletter', 'NewsletterController');

    Route::resource('user', 'UserController');

    Route::resource('wishlist', 'WishlistController');

    Route::resource('attachment', 'AttachmentController');

    Route::resource('setting', 'SettingController');

    Route::get('attachment/get/image', ['as' => 'api.attachment.get.image', 'uses' => 'AttachmentController@getImage']);

    Route::post('upload/image', ['as' => 'api.attachment.upload.image', 'uses' => 'AttachmentController@uploadImage']);

    Route::post('upload/file', ['as' => 'api.attachment.upload.file', 'uses' => 'AttachmentController@uploadFile']);

    Route::post('sellproperty', ['as' => 'sellproperty.store', 'uses' => 'PropertyController@sellProperty']);

    Route::post('property/delete/{id}', ['as' => 'api.property.delete', 'uses' => 'PropertyController@delete']);

    Route::post('property_meta/thumb', ['as' => 'api.thumb.store', 'uses' => 'PropertyMetaController@thumb']);

    Route::post('translate/{to}',['as' => 'api.translate', 'uses' => 'BingTranslateController@trans']);

    Route::post('property/remove', ['as' => 'api.property.remove', 'uses' => 'PropertyController@remove']);

    Route::post('property/set_status', ['as' => 'api.property.set_status', 'uses' => 'PropertyController@setStatus']);

    Route::post('enquiry/remove', ['as' => 'api.enquiry.remove', 'uses' => 'EnquiryController@remove']);

    Route::post('customer/remove', ['as' => 'api.customer.remove', 'uses' => 'CustomerController@remove']);

    Route::post('testimony/remove', ['as' => 'api.testimony.remove', 'uses' => 'TestimonyController@remove']);

    Route::post('contact/remove', ['as' => 'api.contact.remove', 'uses' => 'ContactController@remove']);

    Route::post('newsletter/remove', ['as' => 'api.newsletter.remove', 'uses' => 'NewsletterController@remove']);

    Route::post('post/remove', ['as' => 'api.post.remove', 'uses' => 'PostController@remove']);

    Route::post('user/remove', ['as' => 'api.user.remove', 'uses' => 'UserController@remove']);

    Route::post('branch/remove', ['as' => 'api.branch.remove', 'uses' => 'BranchController@remove']);


});


// Back-End
Route::group(['middleware' => 'auth'], function () {

    Route::group(['prefix' => 'admin'], function () {

        // dashbord
        Route::get('/', function() {

            return redirect('/admin/dashboard');
        });

        Route::get('dashboard',['as' => 'admin.dashboard', 'uses' => 'AdminController@dashboard']);

        // property
        Route::get('properties/{term?}',['as' => 'admin.properties', 'uses' => 'AdminController@properties'])->where('term', '(.*)');

        // enquiry
        Route::get('enquiries/{term?}',['as' => 'admin.enquiries', 'uses' => 'AdminController@enquiries']);


        // customer
        Route::get('customers/{term?}',['as' => 'admin.customers', 'uses' => 'AdminController@customers']);

        // Page
        Route::get('pages/{term?}',['as' => 'admin.pages', 'uses' => 'AdminController@pages']);

        // Post
        Route::get('blog/{term?}',['as' => 'admin.posts', 'uses' => 'AdminController@posts']);

        // my-account
        Route::get('my-account',['as' => 'admin.my_account', 'uses' => 'AdminController@my_account']);

        // accounts
        Route::get('accounts',['as' => 'admin.accounts', 'uses' => 'AdminController@accounts']);

        // branches
        Route::get('branches',['as' => 'admin.branches', 'uses' => 'AdminController@branches']);

        // setting
        Route::get('settings',['as' => 'admin.setting', 'uses' => 'AdminController@settings']);

        // about
        Route::get('about',['as' => 'admin.about', 'uses' => 'AdminController@about']);


        // PDF Export
        Route::group(['prefix' => 'pdf'], function () {

            Route::get('property/{id}', ['as' => 'admin.pdf.property', 'uses' => 'PdfController@property']);
        });

        Route::group(['prefix' => 'export'], function () {

            Route::group(['prefix' => 'property'], function () {

                Route::post('csv', ['as' => 'export.property.csv', 'uses' => 'PropertyController@export']);

                Route::post('pdf', ['as' => 'export.property.pdf', 'uses' => 'PropertyController@exportPDF']);

                Route::get('pdf', function () {

                    $property = \App\Property::find(1);

                    return view('pdf.property', compact('property'));
                });
            });

            Route::group(['prefix' => 'enquiry'], function () {

                Route::post('csv', ['as' => 'export.enquiry.csv', 'uses' => 'EnquiryController@export']);
            });

            Route::group(['prefix' => 'customer'], function () {

                Route::post('csv', ['as' => 'export.customer.csv', 'uses' => 'CustomerController@export']);
            });

            Route::group(['prefix' => 'testimony'], function () {

                Route::post('csv', ['as' => 'export.testimony.csv', 'uses' => 'TestimonyController@export']);
            });

            Route::group(['prefix' => 'contact'], function () {

                Route::post('csv', ['as' => 'export.contact.csv', 'uses' => 'ContactController@export']);
            });

            Route::group(['prefix' => 'post'], function () {

                Route::post('csv', ['as' => 'export.post.csv', 'uses' => 'PostController@export']);
            });

            Route::group(['prefix' => 'page'], function () {

                Route::post('csv', ['as' => 'export.page.csv', 'uses' => 'PageController@export']);
            });

            Route::group(['prefix' => 'user'], function () {

                Route::post('csv', ['as' => 'export.user.csv', 'uses' => 'UserController@export']);
            });

            Route::group(['prefix' => 'branch'], function () {

                Route::post('csv', ['as' => 'export.branch.csv', 'uses' => 'BranchController@export']);
            });

            Route::group(['prefix' => 'newsletter'], function () {

                Route::post('csv', ['as' => 'export.newsletter.csv', 'uses' => 'NewsletterController@export']);
            });

        });

        // Support Ticket
        Route::post('send_ticket', ['as' => 'admin.send_ticket' , 'uses' => function (Illuminate\Http\Request $request) {

            $user = \Auth::user()->get();

            Mail::raw($request->message, function ($m) use ($user, $request) {

                $m->from($user->email, $user->firstname);

                $m->to(\Config::get('mail.support'), 'Support')->subject('KIBARER Ticket: '. $request->subject);

            });

            return response()->json(array('status' => 200, 'monolog' => array('title' => 'success', 'message' => 'Your message has been sent successfully.')));
            // return redirect()->back();

        }]);

    });

});


// User Auth
Route::controllers([

    'auth' => 'Auth\AuthController',

    'password' => 'Auth\PasswordController',
]);


// Front-End
Route::group(['prefix' => Config::get('app.locale_prefix')], function() {

    Route::get('currency/{currrency}', ['as' => 'set_currency', 'uses' => function ($currency) {

        Session::set('currency', $currency);

        // return Session::get('currency');

        return redirect()->back();
    }]);

resources/views/pages/about.blade.php
@extends('index')

@section('meta_description', $page->meta_description)
@section('meta_keyword', $page->meta_keyword)

@section('content')

<div class="bc-bg">
    <ul class="breadcrumb container">
        <li><a href="{{ url() }}">Home</a></li>
        <li class="active">{{ $page->lang()->title }}</li>
    </ul>
</div>
<div class="line-top"><h3><small>{{ $page->lang()->title }}</small></h3></div>

<div class="container">
    <h3>{{ $page->lang()->title }}</h3>
</div>

@endsection

@section('scripts')
<script>
    Kibarer.home();
</script>
@endsection

resources/views/pages/account-setting.blade.php
@extends('index')
@section('content')
<!-- breadcrumb -->
<section class="breadcrumb" style="background-image:url('assets/img/testimonials-bg.jpg');">
    <div class="breadcrumb-holder">
        <div class="page-title ta-center">
            <h3 class="white">
                Account Setting
            </h3>
            <p class="white fw-300">
                Find your property in the different area of Bali
            </p>
        </div>
    </div>
</section>

<!-- MAIN CONTAINER -->
<div id="content"> 

    <!-- BLOG & TESTIMONIALS -->
    <section class="bottom-section flexbox flexbox-wrap justify-between">
        
        @include('fragments.account-sidebar')

        <section class="w66">

            <div class="account-right-content">
                <div class="profile-stting">
                   <h1 class="title">Profile Setting</h1>
                   <div class="title-border-bottom"></div>
                   <div class="kesato-form">

                        {!! Form::open(['url' => route('api.customer.update', ['id' => $customer->id, 'type' => 'profile', 'sess' => 'front']), 'id' => 'validation-form', 'class' => 'form-profile']) !!}
                        {!! method_field('put') !!}

                           <div class="form-body">
                               <div class="frm-row">
                                   <div class="section colm colm6">
                                       <label for="reg_firstname" class="field prepend-icon">
                                           <input value="{{ $customer->firstname }}" type="text" name="firstname" id="reg_firstname" class="pl-15 gui-input" placeholder="First name">
                                       </label>
                                   </div>
                                   <div class="section colm colm6">
                                       <label for="reg_lastname" class="field prepend-icon">
                                           <input value="{{ $customer->lastname }}" type="text" name="lastname" id="reg_lastname" class="gui-input" placeholder="Last name">
                                       </label>
                                   </div>
                               </div>
                       <!--         <div class="section">
                                   <label for="reg_email" class="field prepend-icon">
                                       <input value="{{ $customer->email }}" type="email" name="email" id="reg_email" class="gui-input" placeholder="Email address">
                                   </label>
                               </div> -->
                               <div class="section">
                                   <label for="reg_phone" class="field prepend-icon">
                                       <input value="{{ $customer->phone }}" type="tel" name="phone" id="reg_phone" class="gui-input phone-group" placeholder="Phone number">
                                   </label>
                               </div>
                               
                               <div class="section">
                                   <label for="reg_address" class="field prepend-icon">
                                       <textarea class="gui-textarea" id="reg_address" name="address" placeholder="Address">{{ $customer->address }}</textarea>
                                   </label>
                               </div>
                               <div class="section">
                                   <label for="reg_phone" class="field prepend-icon">
                                       <input value="{{ $customer->city }}" type="tel" name="location" id="reg_phone" class="gui-input phone-group" placeholder="Location">
                                   </label>
                               </div>

                           </div><!-- end .form-body section -->

                           <div class="form-footer">
                               <button id="save-profile" type="submit" class="button btn-primary">{{ trans('word.save') }}</button>
                           </div>
                       {!! Form::close() !!}

                   </div><!-- END KESATO FORM -->
               </div>
               
                <div class="account-setting">
                    <h1 class="title">Account Setting</h1>
                    <div class="title-border-bottom"></div>
                    <div class="kesato-form">

                        {!! Form::open(['url' => route('api.customer.update', ['id' => $customer->id, 'type' => 'account', 'sess' => 'front']), 'id' => 'validation-form', 'class' => 'form-account']) !!}
                        {!! method_field('put') !!}

                            <div class="form-body">
                                <div class="section">
                                    <label for="reg_email" class="field prepend-icon">
                                        <input value="{{ $customer->email }}" type="email" name="email" id="reg_email" class="gui-input" placeholder="Email address" readonly>
                                    </label>
                                </div>
                                
                                <div class="section">
                                    <label for="reg_password" class="field prepend-icon">
                                        <input type="password" name="password" id="reg_password" class="gui-input" placeholder="Password">
                                    </label>
                                </div>
                                <div class="section">
                                    <label for="reg_repeatPassword" class="field prepend-icon">
                                        <input type="password" name="password_confirmation" id="reg_repeatPassword" class="gui-input" placeholder="Confirmation password">
                                    </label>
                                </div>             
                            </div><!-- end .form-body section -->

                            <div class="form-footer">
                                <button id="save-account" type="submit" class="button btn-primary">{{ trans('word.save') }}</button>
                            </div>
                        {!! Form::close() !!}

                    </div><!-- END KESATO FORM -->
                </div>
                
            </div>
        </section>
    </section>
</div>

@endsection

@section('scripts')
<script>
  
$(document).on('submit', '.form-profile', function(event) {
  event.preventDefault();
  /* Act on the event */

  $('.form-profile #notif-success').remove();

  var btn = $('#save-profile'),
  btn_word = btn.html(),
  frm = $(this),
  data = frm.serialize();

  btn.html("{{ trans('word.sending') }}");

  $.post(frm.attr('action'), data, function(data, textStatus, xhr) {
    /*optional stuff to do after success */
    if (data.status == 200) {

      var notif = '<em id="notif-success" class="state-success" style="color: green;">Data has been saved successfully.</em>';

      frm.append(notif);

    } else {

    }

    btn.html(btn_word);

  });

});

$(document).on('submit', '.form-account', function(event) {
  event.preventDefault();
  /* Act on the event */

  $('.form-account #notif-success').remove();

  var btn = $('#save-account'),
  btn_word = btn.html(),
  frm = $(this),
  data = frm.serialize();

  btn.html("{{ trans('word.sending') }}");

  $.post(frm.attr('action'), data, function(data, textStatus, xhr) {
    /*optional stuff to do after success */
    if (data.status == 200) {

      var notif = '<em id="notif-success" class="state-success" style="color: green;">Data has been saved successfully.</em>';

      $('input[type=password]').val('');

      frm.append(notif);

    } else {

    }

    btn.html(btn_word);

  });

});

</script>

@endsection

resources/views/pages/account.blade.php
@extends('index')
@section('content')

<!-- breadcrumb -->
<section class="breadcrumb" style="background-image:url('assets/img/testimonials-bg.jpg');">
    <div class="breadcrumb-holder">
        <div class="page-title ta-center">
            <h3 class="white">
                Account Dashboard
            </h3>
            <p class="white fw-300">
                Find your property in the different area of Bali
            </p>
        </div>
    </div>
</section>

<!-- MAIN CONTAINER -->
<div id="content"> 
    
    <section class="bottom-section flexbox flexbox-wrap justify-between">
    <!-- BLOG & TESTIMONIALS -->
        @include('fragments.account-sidebar')

        <section class="w66">

            <div class="account-right-content">
                <div class="dashboard-holder">
                    <div class="overview-holder flexbox flexbox-wrap">
                        <div class="wishlist-list-holder">
                            <a href="{{ route('account.wishlist', ['account' => trans('url.account'), 'wishlist' => trans('url.wishlist')]) }}">
                                <div class="wishlist-main">
                                    <i class="fa fa-heart"></i> <br> <span class="numeric">{{ count($customer->wishlists) }}</span> <br><br> <span class="title">Wishlist</span>
                                </div>
                            </a>
                        </div>
                        <div class="villa-list-holder">
                            <a href="{{ route('account.wishlist', ['account' => trans('url.account'), 'wishlist' => trans('url.wishlist'), 'category' => 'villa']) }}">
                            <div class="villa-main">
                                <i class="fa fa-home"></i> <br> <span class="numeric">{{ count($customer->wishlists) }}</span> <br><br> <span class="title">Villa</span>
                            </div>
                            </a>
                        </div>
                        <div class="land-list-holder">
                            <a href="{{ route('account.wishlist', ['account' => trans('url.account'), 'wishlist' => trans('url.wishlist'), 'category' => 'land']) }}">
                            <div class="land-main">
                                <i class="fa fa-map-marker"></i> <br> <span class="numeric">{{ count($customer->wishlists) }}</span> <br><br> <span class="title">Land</span>
                            </div>
                            </a>
                        </div>
                    </div>

                    <div class="map-holder">
                        <div id="map-contact" style="width:100%; height: 400px;"></div>
                    </div>
                </div>
            </div>

        </section>
    </section>
</div>

@endsection

@section('scripts')
<script>
    Kibarer.initContact();
</script>
@endsection

resources/views/pages/blog-view.blade.php
@extends('index')

@section('content')

<div id="content">
    
    <div class="blog">
        <div class="blog-content">
            
            <article class="blog-list">
                <!-- <div class="thumbnail"><img src="assets/img/blog-thumbnail.jpg"></div> -->
                <div class="title">{{ $post->lang()->title }}</div>
                <div class="sub">Category : Adventure | Posted on {{ $post->created_at->format('M d, Y') }}</div>
                <div class="desc">
                    <p>{!! $post->lang()->content !!}</p>
                </div>
            </article>

        </div>
    
        @include('fragments.blog-sidebar')
    </div><!-- END BLOG --> 
</div><!-- END MAIN -->
@endsection

@section('scripts')

@stop

resources/views/pages/contact.blade.php
@extends('index')


@section('content')
<section class="breadcrumb" style="background-image:url('assets/img/testimonials-bg.jpg');">
    <div class="breadcrumb-holder">
        <div class="page-title ta-center">
            <h3 class="white">
                {{ trans('word.breadcrumb_contact') }}
            </h3>
            <p class="white fw-300">
                Find your property in the different area of Bali
            </p>
        </div>
    </div>
</section>

<div id="contact-main">
   
    <div class="map-property-box">
        <div id="map-contact" style="width:100%; height: 400px;"></div>   
    </div><!-- END LOGIN BOX -->
    
    <div id="content" class="contact-holder">
        <div class="input-propety-box">
            <div class="input-holder flexbox">
                
                <div class="contact-form">
                    <h1>Send us an email</h1>
                    <div class="kesato-form">
                            {!! Form::open(['url' => route('api.message.store'), 'id' => 'validation-form']) !!}
                            <div class="form-body">
                                <div class="frm-row">
                                    <div class="section colm colm6">
                                        <label for="sell_firstname" class="field prepend-icon">
                                            <input value="{{ old('firstname') }}" type="text" name="firstname" id="sell_firstname" class="pl-15 gui-input" placeholder="First name">
                                        </label>
                                    </div>
                                    <div class="section colm colm6">
                                        <label for="sell_lastname" class="field prepend-icon">
                                            <input value="{{ old('lastname') }}" type="text" name="lastname" id="sell_lastname" class="gui-input" placeholder="Last name">
                                        </label>
                                    </div>
                                </div>
                                <div class="section">
                                    <label for="sell_email" class="field prepend-icon">
                                        <input value="{{ old('email') }}" type="email" name="email" id="sell_email" class="gui-input" placeholder="Email address">
                                    </label>
                                </div>

                                <div class="section">
                                    <label for="sell_desc" class="field prepend-icon">
                                        <textarea class="gui-textarea" id="sell_desc" name="message" placeholder="Description">{{ old('message') }}</textarea>
                                    </label>
                                </div>

                                <div class="section">
                                  <label for="" class="field prepend-icon">
                                      <div class="g-recaptcha" data-sitekey="6Lf8DBsTAAAAAOwOKY1jXnTcC5fL5NVkaw3TkrKS" style=""></div>    
                                  </label>
                                </div>
                  
                            </div><!-- end .form-body section -->

                            <div class="form-footer">
                                <button type="submit" class="button btn-primary">{{ trans('word.send') }}</button>
                            </div>
                            {!! Form::close() !!}
                    </div><!-- END KESATO FORM -->
                </div>
                
                <div class="content">
                    <?php $company_contact = json_decode(\File::get(storage_path('json/general_info.json'))); ?>
                    <p class="desc">
                        {{ trans('notification.contact_description') }}
                    </p>
                    <div class="email">
                        <h6 class="title"> {{ trans('word.email') }} </h6>
                        <div class="title-border-bottom"></div>
                        <a href="mailto:{{ $company_contact->email }}">{{ $company_contact->email }}</a>
                    </div>
                    <div class="phone">
                        <h6 class="title"> {{ trans('word.phone') }} </h6>
                        <div class="title-border-bottom"></div>
                        <a href="tel:623614741212">{{ $company_contact->phone }}</a>
                    </div>
                    <div class="address">
                       <h6 class="title"> {{ trans('word.address') }} </h6>
                        <div class="title-border-bottom"></div>
                        <p>{{ $company_contact->address }}</p>
                    </div>
                </div>
                
            </div>
        </div><!-- ENG REGISTER BOX -->

    </div><!-- END ACCOUNT -->
</div><!-- END MAIN -->

@endsection


@section('scripts')
    <script src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
	<script src='https://www.google.com/recaptcha/api.js'></script>
	<script type="text/javascript">
    
      Kibarer.initContact();
      
      $(document).on('click', 'button[type=submit]', function(event) {
        event.preventDefault();
        /* Act on the event */

        $('.state-error').remove();

        var word = $(this).html();

        console.log('submit clicked');

        $(this).html("{{ trans('word.sending') }}");

        var frm = $('#validation-form'),
            url = frm.attr('action'),
            data = frm.serialize();

        $.post(url, data, function(data, textStatus, xhr) {

          if (data.status == 200) {
            
            console.log(data);

            $('input[name=firstname]').val('');
            $('input[name=lastname]').val('');
            $('input[name=email]').val('');
            $('textarea').val('');

          } else {

            console.log(data);

            if (data.monolog.message.firstname) {
              var notif = '<em for="sell_firstname" class="state-error" style="color: red;">' + data.monolog.message.firstname + '</em>';
              $('input[name=firstname]').closest('.section').append(notif);
            }
            if (data.monolog.message.lastname) {
              var notif = '<em for="sell_lastname" class="state-error" style="color: red;">' + data.monolog.message.lastname + '</em>';
              $('input[name=lastname]').closest('.section').append(notif);
            }
            if (data.monolog.message.email) {
              var notif = '<em for="sell_email" class="state-error" style="color: red;">' + data.monolog.message.email + '</em>';
              $('input[name=email]').closest('.section').append(notif);
            }
            if (data.monolog.message['g-recaptcha-response']) {
                if(data.monolog.message['g-recaptcha-response'].length > 1){
                    var notif = '<em for="sell_recaptcha" class="state-error" style="color: red;">' + data.monolog.message['g-recaptcha-response'][1] + '</em>';
                }
                else{
                    var notif = '<em for="sell_recaptcha" class="state-error" style="color: red;">' + data.monolog.message['g-recaptcha-response'][0] + '</em>';
                }
                
                $('.g-recaptcha').closest('.section').append(notif);
            }

          }

          $('button[type=submit]').html(word);

        });

      });


	</script>
@endsection

resources/views/pages/register-success.blade.php
@extends('index')

@section('content')
<div id="content">
    <div class="notification">
        <div class="success">
            <div class="icon">
                <i class="fa fa-check-circle"></i>
            </div>
            <h1 class="title">Registered Success</h1>
            <div class="desc">
                {{ trans('notification.check_email') }}
            </div>
            <a href="{{ route('login', trans('url.login')) }}" class="login-link">{{ trans('word.login') }}</a>
        </div>
        
        
    </div><!-- END ACCOUNT -->
</div><!-- END MAIN -->

@endsection